# Generated by Django 4.1.2 on 2022-10-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('short_description', models.CharField(max_length=250)),
                ('pdf', models.FileField(upload_to='')),
                ('altitude', models.IntegerField()),
                ('gallery', models.ImageField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
