# Generated by Django 4.1.2 on 2022-10-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('short_description', models.CharField(max_length=250)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('altitude', models.IntegerField()),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Trek',
        ),
    ]
