# Generated by Django 4.1.2 on 2022-10-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0002_treks_delete_trek'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treks',
            options={'verbose_name_plural': 'Treks'},
        ),
    ]
