# Generated by Django 4.1.2 on 2022-10-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0005_treks_day1_treks_day2_treks_day3_treks_day4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treks',
            name='long_description',
            field=models.CharField(default=False, max_length=100000),
        ),
    ]
