# Generated by Django 4.1.2 on 2022-10-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0006_alter_treks_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treks',
            name='day1',
            field=models.CharField(blank=True, default=False, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='treks',
            name='day2',
            field=models.CharField(blank=True, default=False, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='treks',
            name='day3',
            field=models.CharField(blank=True, default=False, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='treks',
            name='day4',
            field=models.CharField(blank=True, default=False, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='treks',
            name='day5',
            field=models.CharField(blank=True, default=False, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='treks',
            name='day6',
            field=models.CharField(blank=True, default=False, max_length=2500, null=True),
        ),
    ]
