# Generated by Django 4.1.2 on 2022-10-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0007_alter_treks_day1_alter_treks_day2_alter_treks_day3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treks',
            old_name='gallery',
            new_name='gallery1',
        ),
        migrations.AddField(
            model_name='treks',
            name='gallery2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='treks',
            name='gallery3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
